/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as StoreLookbookRouteImport } from './routes/_store.lookbook'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as StoreProdutosIndexRouteImport } from './routes/_store.produtos.index'
import { Route as StoreMarcasIndexRouteImport } from './routes/_store.marcas.index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as StoreProdutosSlugRouteImport } from './routes/_store.produtos.$slug'
import { Route as StoreMarcasSlugRouteImport } from './routes/_store.marcas.$slug'
import { Route as AdminProdutosIdEditarRouteImport } from './routes/admin.produtos.$id.editar'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const StoreLookbookRoute = StoreLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => StoreRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProdutosIndexRoute = StoreProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMarcasIndexRoute = StoreMarcasIndexRouteImport.update({
  id: '/marcas/',
  path: '/marcas/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProdutosSlugRoute = StoreProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMarcasSlugRoute = StoreMarcasSlugRouteImport.update({
  id: '/marcas/$slug',
  path: '/marcas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const AdminProdutosIdEditarRoute = AdminProdutosIdEditarRouteImport.update({
  id: '/produtos/$id/editar',
  path: '/produtos/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lookbook': typeof StoreLookbookRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/': typeof AdminIndexRoute
  '/marcas/$slug': typeof StoreMarcasSlugRoute
  '/produtos/$slug': typeof StoreProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/marcas/': typeof StoreMarcasIndexRoute
  '/produtos/': typeof StoreProdutosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/lookbook': typeof StoreLookbookRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/marcas/$slug': typeof StoreMarcasSlugRoute
  '/produtos/$slug': typeof StoreProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/marcas': typeof StoreMarcasIndexRoute
  '/produtos': typeof StoreProdutosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/lookbook': typeof StoreLookbookRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/marcas/$slug': typeof StoreMarcasSlugRoute
  '/_store/produtos/$slug': typeof StoreProdutosSlugRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/_store/marcas/': typeof StoreMarcasIndexRoute
  '/_store/produtos/': typeof StoreProdutosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lookbook'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/marcas'
    | '/admin/'
    | '/marcas/$slug'
    | '/produtos/$slug'
    | '/admin/produtos/novo'
    | '/marcas/'
    | '/produtos/'
    | '/admin/produtos/'
    | '/admin/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/lookbook'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/marcas'
    | '/'
    | '/admin'
    | '/marcas/$slug'
    | '/produtos/$slug'
    | '/admin/produtos/novo'
    | '/marcas'
    | '/produtos'
    | '/admin/produtos'
    | '/admin/produtos/$id/editar'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/_store/lookbook'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/marcas'
    | '/_store/'
    | '/admin/'
    | '/_store/marcas/$slug'
    | '/_store/produtos/$slug'
    | '/admin/produtos/novo'
    | '/_store/marcas/'
    | '/_store/produtos/'
    | '/admin/produtos/'
    | '/admin/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/lookbook': {
      id: '/_store/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof StoreLookbookRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/produtos/': {
      id: '/_store/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof StoreProdutosIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/marcas/': {
      id: '/_store/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof StoreMarcasIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/produtos/$slug': {
      id: '/_store/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof StoreProdutosSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/marcas/$slug': {
      id: '/_store/marcas/$slug'
      path: '/marcas/$slug'
      fullPath: '/marcas/$slug'
      preLoaderRoute: typeof StoreMarcasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/produtos/$id/editar': {
      id: '/admin/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/admin/produtos/$id/editar'
      preLoaderRoute: typeof AdminProdutosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface StoreRouteChildren {
  StoreLookbookRoute: typeof StoreLookbookRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreMarcasSlugRoute: typeof StoreMarcasSlugRoute
  StoreProdutosSlugRoute: typeof StoreProdutosSlugRoute
  StoreMarcasIndexRoute: typeof StoreMarcasIndexRoute
  StoreProdutosIndexRoute: typeof StoreProdutosIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreLookbookRoute: StoreLookbookRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreMarcasSlugRoute: StoreMarcasSlugRoute,
  StoreProdutosSlugRoute: StoreProdutosSlugRoute,
  StoreMarcasIndexRoute: StoreMarcasIndexRoute,
  StoreProdutosIndexRoute: StoreProdutosIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminProdutosIdEditarRoute: typeof AdminProdutosIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminProdutosIdEditarRoute: AdminProdutosIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
